# Generated by Django 5.0.6 on 2025-06-03 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('call_sid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ultravox_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('session_type', models.CharField(choices=[('skill_discovery', 'Skill Discovery'), ('availability_check', 'Availability Check'), ('session_booking', 'Session Booking'), ('session_management', 'Session Management'), ('profile_update', 'Profile Update'), ('general_inquiry', 'General Inquiry')], default='skill_discovery', max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('conversation_data', models.JSONField(default=dict, help_text='Stores conversation context and results')),
                ('ai_response_count', models.PositiveIntegerField(default=0)),
                ('user_input_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('user_input', 'User Input'), ('ai_response', 'AI Response'), ('system_action', 'System Action'), ('api_call', 'API Call'), ('booking_attempt', 'Booking Attempt'), ('skill_search', 'Skill Search'), ('availability_check', 'Availability Check')], max_length=50)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order of interaction in the session')),
                ('user_input', models.TextField(blank=True, help_text='What the user said')),
                ('ai_response', models.TextField(blank=True, help_text='What the AI responded')),
                ('system_action', models.TextField(blank=True, help_text='Any system actions taken')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context and data')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in understanding', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voice_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='voice_ai.voicesession')),
            ],
            options={
                'ordering': ['voice_session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSessionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('skill_found', 'Skill Found'), ('session_booked', 'Session Booked'), ('availability_provided', 'Availability Provided'), ('profile_updated', 'Profile Updated'), ('information_provided', 'Information Provided'), ('no_action', 'No Action Taken'), ('error_occurred', 'Error Occurred')], max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('skills_found', models.JSONField(default=list, help_text='List of skills found during discovery')),
                ('sessions_booked', models.JSONField(default=list, help_text='List of sessions booked')),
                ('availability_data', models.JSONField(default=dict, help_text='Availability information provided')),
                ('summary', models.TextField(help_text='Human-readable summary of what was accomplished')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='voice_ai.voicesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['user', 'session_type'], name='voice_ai_vo_user_id_aba914_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['status', 'created_at'], name='voice_ai_vo_status_3661b1_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['call_sid'], name='voice_ai_vo_call_si_83c145_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['voice_session', 'sequence_number'], name='voice_ai_vo_voice_s_73568a_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['interaction_type', 'timestamp'], name='voice_ai_vo_interac_bcfb89_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesessionresult',
            index=models.Index(fields=['result_type', 'success'], name='voice_ai_vo_result__cdc4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesessionresult',
            index=models.Index(fields=['created_at'], name='voice_ai_vo_created_1d6ca9_idx'),
        ),
    ]
