# Generated by Django 5.0.6 on 2025-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.TextField(blank=True, help_text='Describe your availability and preferences', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Your city or location', max_length=100, null=True),
        ),
    ]
