# Generated by Django 5.2.3 on 2025-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicesession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('connecting', 'Connecting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('simulated', 'Simulated (Development)')], default='initiated', max_length=20),
        ),
    ]
